In [ ]:
from transformers import TFBertModel

In [ ]:
from transformers import BertTokenizer

In [ ]:
model_name = "bert-large-uncased"

In [ ]:
model = TFBertModel.from_pretrained(model_name)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
tokenizer = BertTokenizer.from_pretrained(model_name)

In [ ]:
sentence1 = "I love programming"
sentence2 = "I enjoy coding"

In [ ]:
tokens1 = tokenizer(sentence1, return_tensors="tf")
tokens2 = tokenizer(sentence2, return_tensors="tf")
tokens1,tokens2

({'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101, 1045, 2293, 4730,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>},
 {'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[  101,  1045,  5959, 16861,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>})

In [ ]:
embeddings1 = model(tokens1)["last_hidden_state"]
embeddings2 = model(tokens2)["last_hidden_state"]
embeddings1,embeddings2

(<tf.Tensor: shape=(1, 5, 1024), dtype=float32, numpy=
 array([[[-0.08526117, -0.5764769 , -0.633375  , ..., -0.86952853,
          -0.61489177,  0.13499229],
         [-0.0675717 , -0.5738155 , -0.22566436, ..., -0.24722598,
          -0.14509764, -0.2964073 ],
         [-0.34677207, -0.23050056, -0.06590487, ..., -0.3864914 ,
           0.08854117,  0.06498113],
         [ 0.10635039, -0.15144344, -0.1836153 , ...,  0.10190339,
          -0.7688031 ,  0.15373257],
         [-0.7419942 , -0.22298822, -0.10586639, ..., -0.7624336 ,
          -0.5670841 , -0.16787432]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5, 1024), dtype=float32, numpy=
 array([[[-0.3766582 , -0.9046708 , -0.50428843, ..., -0.9633748 ,
          -0.5423166 ,  0.11364953],
         [-0.0535448 , -0.59047514, -0.40269876, ..., -0.15256438,
          -0.15487303, -0.29055303],
         [-0.21465763, -0.15130925, -0.21339586, ..., -0.33374354,
           0.14531985, -0.3278002 ],
         [ 0.10372909,  0.06824359, -0.

In [ ]:
import numpy as np
mean_embeddings1 = np.mean(embeddings1, axis=1)
mean_embeddings2 = np.mean(embeddings2, axis=1)
mean_embeddings1,mean_embeddings2

(array([[-0.22704975, -0.35104495, -0.24288519, ..., -0.43275523,
         -0.40146708, -0.02211513]], dtype=float32),
 array([[-0.3052229 , -0.2710239 , -0.2720801 , ..., -0.40429968,
         -0.4078783 , -0.18755317]], dtype=float32))

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(mean_embeddings1, mean_embeddings2)
print("Cosine Similarity:", similarity)

Cosine Similarity: [[0.9234959]]


In [ ]:
sentence1 = "I love programming"
sentence2 = "The movie is too bad"


tokens1 = tokenizer(sentence1, return_tensors="tf")
tokens2 = tokenizer(sentence2, return_tensors="tf")
# إيجاد تضمين مفردات كل جملة
embeddings1 = model(tokens1)["last_hidden_state"]
embeddings2 = model(tokens2)["last_hidden_state"]


import numpy as np
mean_embeddings1 = np.mean(embeddings1, axis=1)
mean_embeddings2 = np.mean(embeddings2, axis=1)


from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(mean_embeddings1, mean_embeddings2)

print("Cosine Similarity:", similarity)

Cosine Similarity: [[0.37942252]]
